# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

current_dir = File.dirname(File.expand_path('../',__FILE__))
configs = YAML.load_file("#{current_dir}/config.yml")
vagrant_config = configs['configs']


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "master" do |machine|
    machine.vm.provider 'virtualbox' do |vb|
      # Customize the amount of memory on the VM:
      vb.cpus = vagrant_config['master']['cpu']
      vb.memory = vagrant_config['master']['ram']
    end
    machine.vm.box = 'ubuntu/xenial64'
    machine.vm.hostname = 'master'
    machine.vm.network 'private_network', ip: "192.168.19.40"
    machine.vm.box = "ubuntu/xenial64"

    machine.vm.provision "chef_solo" do |chef|
      chef.add_recipe "init"
      chef.cookbooks_path = ["cookbooks"]
    end

    machine.vm.provision "chef_solo" do |chef|
      chef.add_recipe "k8s-master"
      chef.cookbooks_path = ["cookbooks"]
    end
  end
end
